# Generated by Django 5.2 on 2025-04-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='obj_images/')),
                ('body', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='career',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='icon',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercard',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(upload_to='obj_images/'),
        ),
        migrations.AlterField(
            model_name='career',
            name='photo',
            field=models.ImageField(upload_to='obj_images/'),
        ),
        migrations.AlterField(
            model_name='career',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='obj_images/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='source',
            field=models.ImageField(upload_to='obj_images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('tashkent', 'TASHKENT'), ('bukhara', 'BUXORO'), ('samarqand', 'SAMARQAND'), ('fargona', 'FARGONA'), ('navoiy', 'NAVOIY'), ('andijon', 'ANDIJON'), ('namangan', 'NAMANGAN'), ('jizzax', 'JIZZAX'), ('sirdaryo', 'SIRDARYO'), ('surxandaryo', 'SURXANDARYO'), ('qashqadaryo', 'QASHQADARYO'), ('xorazm', 'XORAZM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='new',
            name='poster',
            field=models.ImageField(upload_to='obj_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderProduct', to='app.product'),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_application_objects', to='app.location'),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobjectimage',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_applications', to='app.partnerapplicationobject'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='obj_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userLoc', to='app.user'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='cv',
            field=models.FileField(upload_to='obj_cv/'),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancyApplication', to='app.vacancy'),
        ),
    ]
