# Generated by Django 5.2 on 2025-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
