# Generated by Django 5.2 on 2025-04-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_history_rename_full_name_career_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='key',
            field=models.ImageField(upload_to='obj_image/'),
        ),
    ]
