# Generated by Django 5.2 on 2025-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_partnerapplication_partnerapplicationimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='area',
            field=models.PositiveIntegerField(default=255),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='floor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
