# Generated by Django 5.2 on 2025-04-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_partnerapplicationobject_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
