# Generated by Django 5.2 on 2025-04-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_partnerapplicationobject_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerapplication',
            old_name='INN',
            new_name='inn',
        ),
    ]
