# Generated by Django 5.2 on 2025-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_new_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
