# Generated by Django 5.2 on 2025-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_new_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='key',
            field=models.ImageField(upload_to='obj_images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('tashkent', 'TASHKENT'), ('bukhara', 'BUXORO'), ('samarqand', 'SAMARQAND'), ('fargona', 'FARGONA'), ('navoiy', 'NAVOIY'), ('andijon', 'ANDIJON'), ('namangan', 'NAMANGAN'), ('jizzax', 'JIZZAX'), ('sirdaryo', 'SIRDARYO'), ('surhandaryo', 'SURXANDARYO'), ('qashqadaryo', 'QASHQADARYO'), ('xorazm', 'XORAZM')], max_length=20),
        ),
    ]
