# Generated by Django 5.2 on 2025-04-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_inn_partnerapplication_inn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lng',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='partnerapplication',
            name='type',
            field=models.CharField(choices=[('legal_entity', 'LEGAL_ENTITY'), ('individual', 'INDIVIDUAL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='area',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_application_objects', to='app.location'),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='rent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partnerapplicationobject',
            name='type',
            field=models.CharField(choices=[('land', 'LAND'), ('commercial_building', 'COMMERCIAL_BUILDING')], max_length=20),
        ),
        migrations.CreateModel(
            name='PartnerApplicationObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='obj_images/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_applications', to='app.partnerapplication')),
            ],
        ),
        migrations.DeleteModel(
            name='PartnerApplicationImage',
        ),
    ]
