# Generated by Django 5.2 on 2025-04-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_location_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerapplication',
            old_name='type',
            new_name='type_partner_app',
        ),
        migrations.RenameField(
            model_name='partnerapplicationobject',
            old_name='type',
            new_name='type_partner_app_obj',
        ),
    ]
