# Generated by Django 5.2 on 2025-04-24 10:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userlocation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
