# Generated by Django 5.2 on 2025-04-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_type_partnerapplication_type_partner_app_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerapplication',
            old_name='type_partner_app',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='partnerapplicationobject',
            old_name='type_partner_app_obj',
            new_name='type',
        ),
    ]
