# Generated by Django 5.2 on 2025-04-24 10:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_usercard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
