# Generated by Django 5.2 on 2025-04-24 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_location_description_alter_vacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to='app.vacancy'),
        ),
    ]
